version: 2
jobs:
  build:
    docker:
      - image: php:7.0-apache
    branches:
      only:
        - master
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Install System Packages
          command: |
            apt-get update && apt-get -y install zip
            apt-get --quiet install --yes python-pip
            pip install -U pip
            pip install awscli
      - run:
          name: zip code
          command: | 
            zip -r source-hoipla.zip .
      - run:
          name: Upload code to S3
          command: aws s3 cp source-hoipla.zip s3://tst-cd-willgroup/hoipla.zip
      - deploy:
          name: Execute CodeDeploy
          command: aws deploy create-deployment --application-name hoipla --deployment-group-name tst-hoipla-deploygroup --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=tst-cd-willgroup,bundleType=zip,key=hoipla.zip --region ap-southeast-1
